service:
  name: quote-machine

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  quote:
    handler: handler.quote
    events:
      - http:
          method: get
          path: quote
